ecart/ecart/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shopping/',include('shopping.urls'))
]

ecart/shopping/urls.py
from django.urls import path
from . import views

app_name='shopping'
urlpatterns=[
    path('home',views.home,name='home'),
    path('product_data',views.product_data_ ,name ='product_data'),
    path('login',views.login,name='login'),
    path('cart_data',views.cart_data,name='cart_data'),
    path('add_to_cart/<str:name>',views.add_to_cart,name='add_to_cart'),
    path('logout',views.logout,name='logout'),
]

ecart/shopping/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class product_data(models.Model):
    name =models.CharField(max_length=256)
    price = models.IntegerField()
    img_link = models.CharField(max_length=125)

class customer(models.Model):
    full_name = models.CharField(max_length=256)
    user = models.ForeignKey(User,on_delete=models.CASCADE)

class cart(models.Model):
    customer = models.ForeignKey(customer,on_delete=models.CASCADE)
    product_id =models.ForeignKey(product_data,on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def subtotal(self):
        return self.product_id.price*self.quantity

ecart/shopping/views.py
from django.shortcuts import render,redirect
from .models import product_data,customer,cart
from django.contrib.auth import authenticate

# Create your views here.
def home(request):
    return render(request,'shopping/home.html')
def product_data_(request):
    if request.session.get('acccess'):
        product_details =product_data.objects.all()
        context = {'product':product_details}
        return render(request,'shopping/home.html',context)
    return redirect('shopping:login')

def add_to_cart(request,name):
    full_name_ =request.session.get('full_name')
    user_object = customer.objects.get(full_name =full_name_)
    product_data_object =product_data.objects.get(name= name)
    cart_ = [c.product_id.name for c in cart.objects.filter(customer = user_object)]
    if name in cart_:
        cart_ =cart.objects.filter(customer =user_object)
        for car in cart_:
            if car.product_id == product_data_object:
                car.quantity = car.quantity + 1
                car.save()
            else:
                cart_ = cart(customer=user_object,product_id=product_data_object)
                cart_.save()
                return redirect('shopping:product_data')
def cart_data(request):
    full_name_ = request.session.get('full_name')
    user_object =customer.objects.get(full_name = full_name_)
    cart_data = cart.objects.filter(customer =user_object)
    cart_total = sum([c.product_id.price * c.quantity for c in cart.objects.filter()])
    context ={'products':cart_data,'cart_total':cart_total}
    return render(request,'shopping/cart.html',context)

def login(request):
    if request.method == 'POST':
        username_ = request.POST.get('username')
        password_ = request.POST.get('password')
        user = authenticate(username=username_,password=password_)

        user_objects =customer.objects.get(user =user)
        if user is not None:
            request.session['full_name'] = user_objects.full_name
            request.session['access'] = True
            return redirect('shopping:product_data')
    return render(request,'shopping/login.html')

def logout(request):
    del request.sessions['full_name']
    del request.sessions['access']
    return redirect('shopping:login')

ecart/shopping/templates/shopping/cart.html
<!DOCTYPE html>
<html>
  <head>
    <title>My Cart</title>
    <style>
      
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
          }

          /* Style the page background and font */
          body {
            background-color: #f5f5f5;
            font-family: Arial, sans-serif;
          }

          /* Style the cart title */
          h1 {
            margin: 20px 0;
            text-align: center;
          }

          /* Style the cart table */
          table {
            margin: 0 auto;
            border-collapse: collapse;
            width: 80%;
          }

          /* Style the table headers */
          thead {
            background-color: #444;
            color: #fff;
          }

          th {
            padding: 10px;
            text-align: left;
          }

          /* Style the table rows */
          tbody tr:nth-child(even) {
            background-color: #f2f2f2;
          }

          td {
            padding: 10px;
          }

          /* Style the table footer */
          tfoot {
            font-weight: bold;
          }

          tfoot tr:first-child {
            border-top: 2px solid #444;
          }

          tfoot td {
            padding: 10px;
          }

          /* Style the checkout button */
          .checkout-btn {
            display: block;
            margin: 20px auto;
            padding: 10px 20px;
            background-color: #444;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
          }

          .checkout-btn:hover {
            background-color: #666;
          }
  </style>
  </head>
  <body>
    <h1>My Cart</h1>
    <table>
      <thead>
        <tr>
          <th>Product</th>
          <th>Price</th>
          <th>Quantity</th>
          <th>Total</th>
        </tr>
      </thead>
      <tbody>
        {% for product in product %}
        <tr>
          <td>
            <img src={{product.product_id.img_link}} width="100" height="100" alt="Product 1">
            {{ product.product_id.name }}
          </td>
          <td>${{ product.product_id.price }}</td>
          <td>{{ product.quantity }}</td>
          <td>{{ product.subtotal }}</td>
        </tr>
        {% endfor %}
      </tbody>
      <tfoot>
        <tr>
          <td colspan="3">Subtotal:</td>
          <td>{{ cart_total }}</td>
        </tr>
      </tfoot>
    </table>
    <button class="checkout-btn">Checkout</button>
  </body>
</html>

ecart/shopping/templates/shopping/home.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>amazon</title>
    <style>
        * {
            box-sizing: border-box
        }

        body {
            font-family: "Lato", sans-serif;
        }

        /* Style the tab */
        .tab {
            float: left;
            border: 1px solid #ccc;
            background-color: #f1f1f1;
            width: 20%;
            height: 100vh;

        }

        .tab-content {
            display: block;
            /* padding: 10px; */
            /* text-align: center; */
        }

        .tab-content h3 {
            text-align: center;
        }
        .cards{
            display: flex;
            flex-direction: row;
            gap :10px;
            margin-top: 50px;
            margin-left: 100px;

        }
    </style>
    
    
  </head>

  <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">ecommerce</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
                </li>
              
            </ul>
            <form class="form-inline my-2 my-lg-0">
               {% csrf_token %}
                <input class="form-control mr-sm-2" type="search" placeholder="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            <div class="logins" id="login_">
                <button type="button" class="btn btn-light"><a href="login"
                        style="color: black;text-decoration:none">login</a></button>
                <button type="button" class="btn btn-light"><a href="{%url 'shopping:logout' %}"
                        style="color: black;text-decoration:none">logout</a></button>
                <button type="button" class="btn btn-light"><a href="{%url 'shopping:cart_data' %}"
                        style="color: black;text-decoration:none"><i class="fa-solid fa-cart-shopping"></i></a></button>

            </div>
            </div>
        </nav>
        <div class="cards">
            {%for product in product%}

                </div> -->
                <div class="card" style="width: 18rem;">
                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxpm3A9IzoUPz6WewB6I6tpM7mg6cYT41v2J18ekWBmA&usqp=CAU&ec=48665701" class="card-img-top" alt="...">
                    <div class="card-body text-center">
                        
                            <h5 class="card-title">brand:{{product.name}}</h5>
                            <p class="card-text">price:{{product.price}}</p>
                        <a href="#" class="btn btn-primary">Add To Cart</a>
                    </div>
              </div>
                
            {%endfor%}
            
        </div>
       
    
       
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

        
      
  </body>
</html>
   

ecart/shopping/templates/shopping/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>login to ecommerce</title>
        <title>Login Page</title>
        <style>
            body {
                background-color: #f1f1f1;
                font-family: Arial, sans-serif;
                font-size: 16px;
                margin: 0;
                padding: 0;
            }
            .container {
                background-color: #fff;
                border-radius: 10px;
                box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
                margin: 50px auto;
                max-width: 500px;
                padding: 50px;
                text-align: center;
            }
            h1 {
                color: #333;
                font-size: 24px;
                margin-bottom: 30px;
            }
            input[type="text"],
            input[type="password"] {
                background-color: #f1f1f1;
                border: none;
                border-radius: 5px;
                box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.2);
                margin-bottom: 20px;
                padding: 10px;
                width: 100%;
            }
            input[type="submit"] {
                background-color: #4CAF50;
                border: none;
                border-radius: 5px;
                box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.2);
                color: #fff;
                cursor: pointer;
                margin-top: 20px;
                padding: 10px;
                width: 100%;
            }
            input[type="submit"]:hover {
                background-color: #3e8e41;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Login</h1>
            <form method="POST" action="{% url 'shopping:login' %}">
                {% csrf_token %}
                <input type="text" name = "username" placeholder="Username">
                <input type="password" name = "password" placeholder="Password">
                <input type="submit" value="Login">
            </form>
        </div>
    </body>
</html>