employee/employee/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('empl/',include('employees.urls'))
]

employee/employees/urls.py
from django.urls import path,include
from . import views

app_name = "employees"
urlpatterns =[
    path('<int:id>',views.employee_details, name='employee_details'),
    path('employees/<int:id>',views.mark_attendance, name='mark_attendance'),
]

employee/employees/models.py
from django.db import models

class Employee(models.Model):
    name = models.CharField(max_length=256)

    def _str_(self):
        return f"{self.name}"
    
class Attendance(models.Model):
    date = models.DateField()
    attendance = models.CharField(max_length=256)
    employee = models.ForeignKey(Employee,on_delete=models.CASCADE)

    def str(self):
        return f"{self.employee} - {self.date} - {self.attendance}"

employee/employees/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from . models import Employee,Attendance

# def show_details(request,id):
#     #this is the R of CRUD
#     employee_ = Employees.objects.get(pk=id)
#     #SELECT * FROM STUDENT WHERE <INSERT PRIMARY KEY HERE>=id
#     attendance = Attendance.objects.filter(employee=employee_)
#     #SELECT * FROM MARKS WHERE STUDENT=(SELECT * FROM STUDENT
#     # WHERE <INSERT PRIMARY KEY HERE>=id)

#     context = {'employee': employee_, 'attendance': attendance}
#     return render(request, 'company/details.html', context)




# Create your views here.
def employee_details(request,id):
    employee_ = Employee.objects.get(id=id)
    attendance=Attendance.objects.filter(employee=employee_)

    context ={'employee':employee_,'attendance':attendance}
    return render(request ,'employees/details.html',context)

def mark_attendance(request,id):
    employee_ = Employee.objects.get(id=id)
    date_ = request.POST.get('date')
    attendance_ =request.POST.get('attendance')
    log =Attendance(employee=employee_,date=date_,attendance=attendance_)
    log.save()
    return redirect('employees:employee_details',employee_.id)

employee/employees/templates/employees/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employee Details</title>
</head>
<body>
    <h1>{{employee.name}}</h1>
        <!-- {{attendence}} -->
        
        <table>
            {%for item in attendance%}
                <tr>
                    <td>{{item.date}}</td>
                    <td>{{item.attendance}}</td>
                </tr>
            {%endfor%}
                    <form method="POST" action="{%url 'employees:mark_attendance' employee.id %}">
                        {% csrf_token %}
                        <tr>
                            <td><input type="date" name="date"></td>
                            <!-- <td><input type="text" name="attendance" placeholder="attendance"/></td> -->
                            <td> <select name="attendance">
                                <option value="Present">Present</option>
                                <option value="Absent">Absent</option>
                            </select>
                        </td>
                       
                        
                        <!-- <td><intput type="submit"  value="markattendance"></td> -->
                        <td><input type="submit" value="Submit"></td>
                    </tr>
                </form>
    </table>


</body>
</html>