first_site/attendence/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('attendence', views.Attendance(), name='attendence'),

]

first_site/fibonacci/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('<int:start>', views.Fibanocii_sequence, name='Fibanocii_sequence'),
    path('withparams', views.get_fibonacii_req_params, name='Fibonocii_withparams'),
    path('processform', views.process_fibonacci_form, name='process_fibonacci_form'),
    path('form', views.show_fibonacci_form, name='fibonacci_collatz_form'),

]

first_site/first_site/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),

    path('hello/',include('sayhello.urls')),

    path('Fibo/', include('fibonacci.urls')),

    path('game/',include('rockpaperscissor.urls')),

    path('gradbook/',include('gradebook.urls')),

    path('attendence/',include('attendence.urls'))



    

    
]

first_site/gradebook/urls.py
from django.urls import path
from . import views

app_name='gradebook'

urlpatterns = [
    path('student/<int:id>', views.student_detail, name='student_detail'),
    path('student/<int:id>/add', views.add_marks, name='add_marks'),
    path('student/<int:id>/delete', views.delete_marks, name='delete_marks'),
    path('student/update/<int:id>',views.update_marks,name='update_marks')
     
]

first_site/rockpaperscissor/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path("game/",views.rock_paper_scissor_function,name="rock_paper_scissor_function")
]

first_site/sayhello/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.say_hello,name='say_hello')
]

first_site/attendence/models.py
from django.db import models

class Attendance(models.Model):
    employee_id = models.IntegerField()
    date = models.DateField()
    status = models.CharField(max_length=10)

first_site/fibonacci/models.py
from django.db import models

# Create your models here.

first_site/gradebook/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length = 256)

    def __str__(self):
        return f'crazy stuff {self.name}'

class Marks(models.Model):
    subject_name = models.CharField(max_length = 128)
    score = models.IntegerField()
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    #having a list of Marks inside every student
    #is the same as having a student inside every Mark

    def __str__(self):
        return f'{self.student} - {self.subject_name} - {self.score}'

first_site/rockpaperscissor/models.py
from django.db import models

# Create your models here.

first_site/sayhello/models.py
from django.db import models

# Create your models here.

first_site/attendence/views.py
from django.shortcuts import render
from attendence.models import Attendance

def employee_attendance_history(request, employee_id):
    attendance_history = Attendance.objects.filter(employee_id=employee_id)
    return render(request, 'attendance/employee_attendance_history.html', {'attendance_history': attendance_history})


# Create your views here.

first_site/fibonacci/views.py
from django.shortcuts import render
from django.http import HttpResponse
from.fibonacci import fibonacci

def Fibanocii_sequence(request,start):
    sequence = fibonacci(start)
    standard_response = f'''
    <!DOCTYPE html>
        <html>

            <head>
                <title>Fibonacii</title>
            </head>

            <body>
                <h2>Fibonacci sequence for {start} </h2>
                <p>{sequence}</p>
            </body>

        </html>
        '''

    return HttpResponse(standard_response)

def get_fibonacii_req_params(request):
    start = int(request.GET.get('start', '70'))
    sequence = fibonacci(start)
    standard_response = f'''
    <!DOCTYPE html>
        <html>

            <head>
                <title>Fibonacci</title>
            </head>

            <body>
                <h2>Fibonacci sequence for {start} </h2>
                <p>{sequence}</p>
            </body>

        </html>
        '''

    return HttpResponse(standard_response)

def process_fibonacci_form(request):
    start = int(request.POST.get('start', '1'))
    sequence = fibonacci(start)
    standard_response = f'''
    <!DOCTYPE html>
        <html>

            <head>
                <title>Fibonacci</title>
            </head>

            <body>
                <h2>Fibonacci sequence for {start} </h2>
                <p>{sequence}</p>
            </body>

        </html>
        '''

    return HttpResponse(standard_response)

def show_fibonacci_form(request):
    return render(request, 'fibonacci/fibonacci.html')

first_site/gradebook/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from .models import Student, Marks
# Create your views here.

def student_detail(request, id):
    #this is the R of CRUD
    student_ = Student.objects.get(pk=id)
    #SELECT * FROM STUDENT WHERE <INSERT PRIMARY KEY HERE>=id
    marks = Marks.objects.filter(student=student_)
    #SELECT * FROM MARKS WHERE STUDENT=(SELECT * FROM STUDENT
    # WHERE <INSERT PRIMARY KEY HERE>=id)

    context = {'student': student_, 'marks': marks}
    return render(request, 'gradebook/gradebook.html', context)

def add_marks(request, id):
    #this is the C of CRUD
    student_ = Student.objects.get(pk=id)

    sub_name_ = request.POST.get('sub_name')
    score_ = request.POST.get('score')

    marks = Marks(student=student_, subject_name=sub_name_, score=score_)
    marks.save()
    return redirect('gradebook:student_detail', student_.id)

def delete_marks(request, id):
    #this is the D of crud
    marks = Marks.objects.get(pk=id)
    marks.delete()
    return redirect('gradebook:student_detail', marks.student.id)

def update_marks(request,id):
    student_=Student.objects.get(pk=id)
    marks = Marks.objects.filter(student=student_)
    name = request.POST.get('name')
    update_name = request.POST.get('sub_name')
    update_score = request.POST.get('score')
    for item in marks:
        if item.subject_name==name:
           item.subject_name=update_name
           item.score=update_score
           item.save()
        item.save()   
    return redirect('gradebook:student_detail', student_.id)

first_site/rockpaperscissor/views.py
from django.shortcuts import render



def rock_paper_scissor_function(request):
    if request.method == 'POST':
        player1_choice = request.POST.get('player1_choice')
        player2_choice = request.POST.get('player2_choice')
        result = ''
        if player1_choice== player2_choice:
            result = "It's a tie!"
        elif player1_choice == 'rock':
            if player2_choice == 'paper':
                result = 'Player 2 wins!'
            else:
                result = 'Player 1 wins!'
        elif player1_choice == 'paper':
            if player2_choice == 'scissors':
                result = 'Player 2 wins!'
            else:
                result = 'Player 1 wins!'
        else:
            if player2_choice == 'rock':
                result = 'Player 2 wins!'
            else:
                result = 'Player 1 wins!'
        context={'result':result}
        return render(request, 'rockpaperscissor/rockpaperscissor.html',context)
    else:
        return render(request, 'rockpaperscissor/rockpaperscissor.html',)
# Create your views here.

first_site/sayhello/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def say_hello(request):
    return HttpResponse("Hello World!!")

first_site/attendence/templates/attendence/attendence.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'base.html' %}

{% block content %}
  <h1>Attendance History for Employee {{ employee_id }}</h1>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      {% for attendance in attendance_history %}
        <tr>
          <td>{{ attendance.date }}</td>
          <td>{{ attendance.status }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

</body>
</html>

first_site/fibonacci/templates/fibonacci/fibonacci.html
<!DOCTYPE html>
<html>
    <body>
        <h3>Fibonacci Form!</h3>
        <form method="POST" action="{% url 'process_fibonacci_form' %}">
            {% csrf_token %}
            <label for="name">Enter your name</label>
            <input type="text" name="name" id="name"><br/>
            <label for="start">Enter starting value</label>
            <input type="text" name="start" id="start"><br/>
            <input type="submit" value="Get Fibonacci Sequence">
        </form>
    </body>
</html>

first_site/gradebook/templates/gradebook/gradebook.html
<!DOCTYPE html>
<html>
    <body>
        <h3>{{student.name}}</h3>
        <table>
            {% for item in marks %}
            <tr>
                <td>{{item.subject_name}}</td>
                <td>{{item.score}}</td>
                <form method="DELETE" action="{% url 'gradebook:delete_marks' item.id%}">
                    <td><input type="submit" value="delete">
                    </td>
                </form>
            </tr>
            {% endfor %}
            <form method="POST" action="{% url 'gradebook:add_marks' student.id %}">
                {% csrf_token %}
                <tr>
                    <td><input type="text" name="sub_name"></td>
                    <td><input type="text" name="score"></td>
                    <td><input type="submit" value="add"></td>
                </tr>
            </form>
            <form method="POST" action="{% url 'gradebook:update_marks' student.id%}">
                {% csrf_token %}
                <tr>
                    <td>name:<input type='text' name ='name' placeholder="name"</td>
                    <td><input type="text" name="sub_name"></td>
                    <td><input type="text" name="score"></td>
                    <td><input type="submit" value="update"></td>
                </tr>

            </form>
        </table>
    </body>
</html>

first_site/rockpaperscissor/templates/rockpaperscissor/rockpaperscissor.html
<!DOCTYPE html>
<html>
<head>
	<title>Rock Paper Scissors</title>
</head>
<body>
	<h1>Rock Paper Scissors</h1>
	{% if result %}
	<p>{{result}}</p>
	{% endif %}
	<form action="{% url 'rock_paper_scissor_function'%}" method="post">
		{% csrf_token %}
		<label>Choose your choice:</label>
		<select name="player1_choice">  
			<option value="rock">rock</option>
			<option value="paper">Paper</option>
			<option value="scissors">scissors</option>
		</select>
        <select  name="player2_choice">
			<option value="rock">rock</option>
			<option value="paper">paper</option>
			<option value="scissors">scissors</option>
		</select>
		<button type="submit">Play!</button>
	</form>
</body>
</html>

first_site/sayhello/templates/sayhello/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello!</title>
</head>
<body>
    
</body>
</html>